const DEFAULT = 'EXCHANGE_RATES';

export const FETCH_DATA_COMPLETE = `${DEFAULT}/FETCH_DATA_COMPLETE`;
export const FETCH_DATA_REQUEST = `${DEFAULT}/FETCH_DATA_REQUEST`;
export const FETCH_DATA_ERROR = `${DEFAULT}/FETCH_DATA_ERROR`;
